### ISSUE TITLE
Rust 対応

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/verification-helper#113]
親 issue: #116

Rust は必要だろ

**Comment by kmyk** [comment]
cc: @yosupo06 @fukatani

**Comment by kmyk** [comment]
@niuez https://github.com/niuez/cp-rust-library https://github.com/niuez/rust-data-structures

**Comment by kmyk** [comment]
あまり交流ないけどこの前おもしろいもの作ってたし @tanakh

**Comment by qryxip** [comment]
私のアイディアを書いておきます。 これを書くにあたり[rust-jp.slack.com](https://rust-jp.slack.com)でアドバイスを貰いました。

#### `compile`, `get_executable_command`

```console
$ rustup run "$VERSION" rustc "$EDITION_OPTION" -C "opt-level=$OPT_LEVEL" -o "$BIN" "$SRC"
```

ただし`$BIN`は`"$(cargo metadata --format-version 1 | jq -r .target_directory)/release/examples/$(basename "$SRC" .rs)"`、`$EDITION_OPTION`は`""`、`$OPT_LEVEL`は`"2"`で

#### `list_attribute`

良くわからないのですがMarkdown生成用のと一緒にmodule docにdoxygen形式で書くようにするのでは駄目でしょうか。 あとはこういう方法しか思い浮かばないです。

````rust
//! ```json, online-judge-verify-helper
//! {
//!   "foo": 42
//! }
//! ```
````

#### `list_dependencies`, `bundle`

Rustの`mod`は構文解析時にファイルの中身がそのまま展開されます。

```rust
mod foo;
```

↓

```
mod foo {
    {{./foo.rsまたは./foo/mod.rsの中身。 両方がある、または両方無いとエラー}}
}
```

このとき`#[path = ".."]`を付けることでマウントする対象を指定することができます。

```rust
#[path = "path/to/foo.rs"]
mod foo;
```

これでmainのやつの上で**必要な分だけ**path指定した`mod`をマウントするのがいいんじゃないかと思います。 ↓の例だと`my_complib`が`lib` crateとしてビルドされますがそれは無視します。 『`lib` crateとしての利用』 → 『直に埋め込んでの利用』の変換をやろうとすると恐らく地獄が発生しそうです。 そもそもあまり嬉しくもないでしょうし。

またCargoでビルドすると`./target`下に`.d`が生成されますがこの例での`znz/thread_local.rs`とかを排することはできないようです。

で、`bundle`はと言うと少しだけ面倒が発生する可能性があります。 `#[path = "path/to/foo.rs"] (pub) mod foo;`または`(pub) mod foo;`を置換する必要があるのですがこれを一発でやるツールはありません。 (マクロごと展開するのはあるけれど`std::println!`のような`std`のマクロも展開して、マクロ越しにしか呼んじゃ駄目な関数等が出現する)

またファイルを辿ってインデントもかける必要もあります。 インデントについては最後にrustfmt (公式フォーマッタ。 今Rustをインストールするともれなく付いてくる)をかけるのでいいんじゃないかと思うのですが競プロerにおいてはrustfmtを使うのは一般的ではないようです。 私なんかはVimキーバインドのnormal modeでの<kbd>ESC</kbd>でフォーマッタがかかるようにしてますがそんなことをしている人は少数でしょうし面倒であるというのは理解できます。

Rustで`cargo-expand-mods`みたいなのをサッと実装するという手もありそうです。

```rust
// my_complib
// ├── examples
// │   └── problem.rs (このファイル) (num_traits.rs, znz/*.rsに依存)
// └── src
//     ├── lib.rs (`mod`以外のアイテムを含まない)
//     ├── num_traits.rs
//     ├── unrelated.rs (problem.rs上にマウントされない)
//     └── znz
//         ├── constant.rs (num_traits.rs, znz/implementation.rsに依存)
//         ├── implementation.rs (num_traits.rsに依存)
//         ├── mod.rs (znz/constant.rs, znz/implementation.rsに依存)
//         └── thread_local.rs (num_traits.rs, znz/implementation.rsに依存。 problem.rsには使われていないはずだがそこは諦める)

fn main() {
    assert_eq!(*(Z::new(1_000_000_006) + Z::new(2)), 1);
}

decl_znz!(Z = Znz<u64, 1_000_000_007>);

//#[path = "../src/num_traits.rs"]
//mod num_traits;
//#[path = "../src/znz/mod.rs"]
//mod znz;

// ↓ 展開

mod znz {
    //! _ℤ/nℤ_

    pub(crate) mod constant {
        //! Represents _ℤ/nℤ_ where _n_ is a **constant value**.

        use crate::num_traits::PrimInt;
        use crate::znz::implementation;

        use std::marker::PhantomData;
        use std::ops::{Add, Deref};

        #[macro_export]
        macro_rules! decl_znz(($name:ident = Znz<$ty:ty, $modulus:literal>) => {
            type $name = crate::znz::constant::Znz<$ty, __Modulus>;

            enum __Modulus {}

            impl crate::znz::constant::PseudoConst for __Modulus {
                type Value = $ty;
                const VALUE: $ty = $modulus;
            }
        });

        pub(crate) trait PseudoConst {
            type Value: Copy;
            const VALUE: Self::Value;
        }

        /// Represents _ℤ/nℤ_ where _n_ is a **constant value**.
        pub(crate) struct Znz<R, M> {
            repr: R,
            phantom: PhantomData<fn() -> M>,
        }

        impl<R: PrimInt, M: PseudoConst<Value = R>> Znz<R, M> {
            pub(crate) fn new(val: R) -> Self {
                Self {
                    repr: val % M::VALUE,
                    phantom: PhantomData,
                }
            }
        }

        impl<R, M> Deref for Znz<R, M> {
            type Target = R;

            fn deref(&self) -> &R {
                &self.repr
            }
        }

        impl<R: PrimInt, M: PseudoConst<Value = R>> Add for Znz<R, M> {
            type Output = Self;

            fn add(self, rhs: Self) -> Self {
                Self::new(implementation::mod_add(*self, *rhs, M::VALUE))
            }
        }
    }

    pub(crate) mod thread_local {
        use crate::num_traits as _;
        use crate::znz::implementation as _;

        //
    }

    pub(super) mod implementation {
        use crate::num_traits::PrimInt;

        pub(super) fn mod_add<T: PrimInt>(lhs: T, rhs: T, modulus: T) -> T {
            (lhs + rhs) % modulus
        }
    }
}

mod num_traits {
    //! Pseudo `num-traits`.

    use std::ops::{Add, Div, Mul, Rem, Sub};

    pub(crate) trait PrimInt: Copy + NumOps + EtcEtc {}

    impl PrimInt for u8 {}
    impl PrimInt for u16 {}
    impl PrimInt for u32 {}
    impl PrimInt for u64 {}
    impl PrimInt for u128 {}
    impl PrimInt for usize {}
    impl PrimInt for i8 {}
    impl PrimInt for i16 {}
    impl PrimInt for i32 {}
    impl PrimInt for i64 {}
    impl PrimInt for i128 {}
    impl PrimInt for isize {}

    pub(crate) trait NumOps<Rhs = Self, Output = Self>:
        Add<Rhs, Output = Output>
        + Sub<Rhs, Output = Output>
        + Mul<Rhs, Output = Output>
        + Div<Rhs, Output = Output>
        + Rem<Rhs, Output = Output>
    {
    }

    impl<T, Rhs, Output> NumOps<Rhs, Output> for T where
        T: Add<Rhs, Output = Output>
            + Sub<Rhs, Output = Output>
            + Mul<Rhs, Output = Output>
            + Div<Rhs, Output = Output>
            + Rem<Rhs, Output = Output>
    {
    }

    pub(crate) trait EtcEtc {}

    impl<T> EtcEtc for T {}
}
```

**Comment by qryxip** [comment]
```console

```

**Comment by kmyk** [comment]
これどうなったんだろう。誰かプルリクを出してほしい

**Comment by qryxip** [comment]
とりあえず[これ](https://github.com/qryxip/cargo-expand-mods/issues/1)を片したついでに試したらrust-analyzer (rls-2.0として開発されているlanguage server)がこんなことに..

![rust-analyzer3](https://user-images.githubusercontent.com/14125495/78819857-daac9e80-7a11-11ea-9b13-8cbfe1089eb6.png)

「`#[path = ".."]`はサポートされているはずでは?」と思って色々試したら

![rust-analzyer](https://user-images.githubusercontent.com/14125495/78819867-dda78f00-7a11-11ea-9502-46da4b9cbc7e.png)

こういうことみたいなのでライブラリはworkspace内(正確には`workspace_directory`下)に入れとく必要があるっぽいですね。 一応ライブラリに関する補間及びhover docが一切効かないのと画面が赤くなる以外に実害はありませんが。 RLSはどうなのかな.. とりあえずrust-analyzerにissue立てられそうなら立ててきます。

**Comment by qryxip** [comment]
「前は大丈夫だった気がする」というよりも

> ```rust
> // my_complib
> // ├── examples
> // │   └── problem.rs (このファイル) (num_traits.rs, znz/*.rsに依存)
> // └── src
> //     ├── lib.rs (`mod`以外のアイテムを含まない)
> //     ├── num_traits.rs
> //     ├── unrelated.rs (problem.rs上にマウントされない)
> //     └── znz
> //         ├── constant.rs (num_traits.rs, znz/implementation.rsに依存)
> //         ├── implementation.rs (num_traits.rsに依存)
> //         ├── mod.rs (znz/constant.rs, znz/implementation.rsに依存)
> //         └── thread_local.rs (num_traits.rs, znz/implementation.rsに依存。 problem.rsには使われていないはずだがそこは諦める)
> ```

踏まなかっただけですね..

**Comment by kmyk** [comment]
記録用 @shino16

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">依存関係の読み取りまではできた気がする（相対パスは非対応） <a href="https://t.co/WXqau7jBMX">pic.twitter.com/WXqau7jBMX</a></p>&mdash; しの (@shino_skycrew) <a href="https://twitter.com/shino_skycrew/status/1299623447274819584?ref_src=twsrc%5Etfw">August 29, 2020</a></blockquote>

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">oj-bundle的なやつ　できたっぽい<br>相対パスは結局非対応でいいかな… <a href="https://t.co/mwMnSh6cVK">pic.twitter.com/mwMnSh6cVK</a></p>&mdash; しの (@shino_skycrew) <a href="https://twitter.com/shino_skycrew/status/1299693912106254336?ref_src=twsrc%5Etfw">August 29, 2020</a></blockquote>

**Comment by kmyk** [comment]
記録用2 @MiSawa

https://github.com/MiSawa/ralgo

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">oj-verify run を rust から使うことに成功した気がする. 酷いハックをかましているので本家にパッチ送れるようなアレではないが…<a href="https://t.co/8YVuqvJA8t">https://t.co/8YVuqvJA8t</a></p>&mdash; みさわ (@Mi_Sawa) <a href="https://twitter.com/Mi_Sawa/status/1288505320055037952?ref_src=twsrc%5Etfw">July 29, 2020</a></blockquote>

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">自分の競プロライブラリをインライン化したいだけなら、RUSTFLAGS=&quot;-Z save-analysis&quot; で cargo 走らせてできるファイルに各コードスパンの定義位置やらなんやら入っているので、それを使うのが正確だと思う</p>&mdash; みさわ (@Mi_Sawa) <a href="https://twitter.com/Mi_Sawa/status/1299347869736943616?ref_src=twsrc%5Etfw">August 28, 2020</a></blockquote>

**Comment by kmyk** [comment]
本体側に Rust のコードを同梱しちゃうとメンテコストが爆発してつらいと思うけど、依存関係解析や単一ファイル化などをすべて Rust で書いて crate などとして公開してもらって、oj-verify からはそれをプラグインとして叩くだけというのはかなりあり。
MiSawa/ralgo は「酷いハック」と言うから oj-verify 側に影響範囲の広いパッチ当ててるのかなと思ってたけど、他の言語と同じ標準のインターフェースに乗る形になってて、かなりきれいに見える。「Rust の unstable な機能を使ってる」とかぐらいなら (メンテできる人の確保さえできれば) 特に問題ないはず。

(なお私は Rust の crate を作るとかは分からないので作業はできません。依然としてプルリク待ちです)

**Comment by qryxip** [comment]
bundleの方をやるにあたって重要だと思っているのが

1. Clippy (静的エラー表示ツール)が動くか
2. rust-analyzer (保管やインテリセンスをやるLSPサーバー)が動くか
3. bundleした状態で動くか
4. 当然であるがエディタや`cat`で開いてコピー&ペースト、よりも手間が少ない

で、私のcargo-expand-modsだと4.が駄目で2.も怪しいという惨状だったので諦めたのですが最近方法をもう一つ思い付きました。この方法だとcargo-expand-modsのときと同じく、各アイテムのパスを探し回って変更する必要がありません。

```toml
[dependencies]
__complib__ = { package = "complib", path = "../complib" } # 誤って`complib`を直接使わないようにリネーム
dummy_attribute = "1.0.0" # ダミーのためだけのproc-macroをCrates.ioに上げておく
```

```rust
// `mod`の深さは最大1という規約でライブラリを書く
#[dummy_attribute::declare_competitive_library("complib")]
pub use __complib__::{algebra, fenwich};
```

↓

```rust
pub mod fenwick {
    pub use crate::algebra;
    pub use crate::numeric;
}

pub mod algebra {
    pub use crate::numeric;
}

pub mod numeric {
    //
}
```

依存関係は最悪手で書けますし、この方法なら`main.rs` → ライブラリの各`mod`の依存は自然な形で手で書けます。

cargo-oj-bundle (?)もちゃんと動きそうに見えるのですが、個人的に相対パスやマクロを普通に使えた方が良いんじゃないかと考えてしまいます。

(なお「コードに表われる相対パスを一つずつずらす」アプローチで、それを真面目にやろうとすると面倒どころではなく地獄だと思います)

[Rustのモジュールを詳細に理解する(4) インポート解決](https://qnighy.hatenablog.com/entry/2019/05/09/190000)

**Comment by shino16** [comment]
ここのissueの存在に今気が付きました…　先にこちらを確認すべきでしたね。

このようなツールを今日作りました。テストが不十分なため期待される動作が正しくできているかも怪しいのですが、README.mdにあるような機能は実現できたと思っています。

https://github.com/shino16/cargo-auto-bundle

**Comment by shino16** [comment]
もともとonline-judge-toolsのことを考えて作ったものではないですが、`list_dependencies`くらいなら[MiSawa/ralgo](https://github.com/MiSawa/ralgo)も参考にしてきちんとしたものが出せるかもしれません。

bundleについてはどのみちまともなものになるとは思えないので、PRを出すつもりはありません。良くてonline-judge-toolsのconfig.tomlに書ける外部ツールくらいかなと思います。

**Comment by qryxip** [comment]
私の方でも昨日言ったやりかたで[cargo-equip](https://github.com/qryxip/cargo-equip)というのを実装してみました。

依存関係の推測は一切せず、ライブラリ側で明示的に指定する形です。指定が欠けている場合はwarningと共にすべてのモジュールを展開します。

また深さ2以降のモジュールはその親や兄弟とと区別しません。

```toml
# lib側

[package.metadata.cargo-equip.mod-dependencies]
"algebra" = []
"bit" = ["algebra"]
"input" = []
```

例としてはこのコードを

```toml
# bin側

[dependencies]
__complib = { package = "complib", path = "/home/ryo/src/local/complib" }
cargo_equip_marker = { path = "/home/ryo/src/github.com/qryxip/cargo-equip/cargo_equip_marker" }
```

```rust
/* aaaaa */
#[cargo_equip::equip]
use ::__complib::{bit::AdditiveBit, input}; /* aaaaa */

fn main() {
    input! {
        n: usize,
        q: usize,
        r#as: [i64; n],
        queries: [(u32, usize, i32); q],
    }

    let mut bit = AdditiveBit::new(n);

    for (i, a) in r#as.into_iter().enumerate() {
        bit.plus(i, a);
    }

    for (kind, v1, v2) in queries {
        match kind {
            0 => {
                let (p, x) = (v1, v2 as i64);
                bit.plus(p, x);
            }
            1 => {
                let (l, r) = (v1, v2 as usize);
                println!("{}", bit.query(l..r));
            }
            _ => unreachable!(),
        }
    }
}
```

このように展開できます。

<https://judge.yosupo.jp/submission/20610>

`#[cargo_equip::equip]`が付いた`use`文を展開します。 `use`にはtrailing colon (`::`)を要求します。そうするとpathの1つめは`extern_crate_name`と言えるのでそこから`dependencies`内のlibを割り出します。 2つめは展開するモジュールの絞り込みに使い、3つめ以降は`use self::..`と置き換えます。

Clippy, rust-analyzer, 展開後のコード, すべて騙せているように思えます。今のところは。

あとやりたいのは

- 依存の推定が無理だとしてもマシな方法で指定できないか
- このAPIならRust使いの夢である手続き型マクロの持ち込みができるのでは
- 設定でon/offできるようにした上でrustfmtをかける
- `#[cfg(..)]`を見て`#[cfg(test)]`とかを除去する。cfgのパーサーは`cargo`クレートじゃなくてもそこそこ人気のやつがある
- 生成したコードを即座にそのワークスペース内でビルドし、テストする。trybuildとかどうやってたっけ...

**Comment by qryxip** [comment]
[README](https://github.com/qryxip/cargo-equip/blob/master/README-ja.md)を書いてcrate.ioにアップしました。テストはこれから書きます。

手で書いた依存関係は

```console
$ cargo metadata --format-version 1 --no-deps | jq '.packages[].metadata."cargo-equip-lib"."mod-dependencies"'
```

として読むことができます。

cargo-auto-bundleとアプローチ(≠ ツール自体)を比べたときの利点欠点はこのあたりでしょうか:

pros:

- 各ファイルの中身を一切弄らないため、壊れにくい。モジュール階層もそのままなので相対パスもマクロも気兼ねなく使える

cons:

- ライブラリの書き方に制限がある (横に広く書く必要がある)

ところで本っ当に今更なんですが、verificationに直接`bundle`を使うのではなく`list_dependencies`通りの絞り込みを行うバンドル方法が1つ以上存在することが重要、という理解でいいんでしょうか...?

**Comment by kmyk** [comment]
> ところで本っ当に今更なんですが、verificationに直接bundleを使うのではなくlist_dependencies通りの絞り込みを行うバンドル方法が1つ以上存在することが重要、という理解でいいんでしょうか...?

なにを確認しようとしているのか理解できませんでした。とりあえず関連しそうな情報を列挙しておきます。

- list_dependencies は実行する必要のあるテストの列挙に使われる。ついでにドキュメント生成にも使われる
- bundle は必ずしも実装される必要はない

**Comment by qryxip** [comment]
`bundle`は`verify`に必須ではないというのは認識していたのですが、`compile`の引数にしている訳ではなさそうだし`verify`側でどう`bundle`を使うのかがわかりませんでした。`oj verify docs`で使ってたんですね。手元で生成して初めて気付きました。なるほどライブラリ側のbundleも何に使うのかと思っていたのですがこういう形なら第三者とかが使いやすくなるという利点がありますね。あとよく見たら`oj-verify run`でもバンドルを実行している。

cargo-equipを使ったそれっぽいセットをとりあえず作ってみました。

[qryxip/oj-verify-playground](https://github.com/qryxip/oj-verify-playground)

![Screenshot1](https://user-images.githubusercontent.com/14125495/91914413-f54e1f80-ecf2-11ea-84d2-32089c6b7bb8.png)

![Screenshot2](https://user-images.githubusercontent.com/14125495/91914420-f97a3d00-ecf2-11ea-9287-a8916865b399.png)

**Comment by qryxip** [comment]
一応整えましたがこれでいいのか感が

<https://qryxip.github.io/oj-verify-playground>

- [x] library → libraryの`list_dependencies` (手で記述。制限あり)
- [x] verification → libraryの`list_dependencies` (↑からcargo-equipの出力を`sed`。cargo-equip側から情報のJSONを吐くことを検討中)
- [ ] libraryの`bundle`
- [x] verificationの`bundle` (cargo-equipで展開)

**Comment by qryxip** [comment]
参考:

[regexident/cargo-modules](https://github.com/regexident/cargo-modules)

> A cargo plugin for showing an overview of a crate's modules.

`cargo modules tree`と`cargo modules graph`のサブコマンドからなる老舗(since 2016)のツールである。`rustc-ap-*`系を用いておりNightly Rustを要求する。`cargo modules tree`はクレート内のモジュールを`tree(1)`のように表示する。

そして`cargo modules graph`はモジュールの依存関係をグラフで出力する。READMEには(当時の)cargo-modules自身に使った図が載っている。

![READMEの画像](https://raw.githubusercontent.com/regexident/cargo-modules/master/dot-preview.png)

これはまさしく我々が求めていたものに見える。しかしREADMEを`blame`するとこの画像が貼られたのは2018月5月、Rust 2018年がリリースされる少し前である。

現在のRustで動作させた場合、このような悲しい図しか得られない。(実際にはモジュール同士は依存しあってるし、さらに言えば`ng`は4つのサブモジュールを持っているはずである)

![なにこれ](https://user-images.githubusercontent.com/14125495/92004614-633f2900-ed7d-11ea-93f4-d4647bba0e1d.png)

いろいろ試した結果だが、Rust 2018では動作しないと言っても良い。ただしなんとかしようとはしている模様。

https://github.com/regexident/cargo-modules/issues/34

これを助けてcargo-modulesを使う、という選択肢がある。

**Comment by kmyk** [comment]
メモ: https://github.com/ngtkana/procon-bundler

<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="ja" dir="ltr">Rust で新しくバンドラを作りなおして、VimScript はこれを呼ぶだけにすることにしました。機能も増えていて、なんと今回は Cargo.toml を読んでコピペ用にモジュールパスを書き換えてくれます。素晴らしいでしょう。（なおマクロは非対応です）<a href="https://t.co/Kq5GVRRRJl">https://t.co/Kq5GVRRRJl</a></p>&mdash; ながたかな (@ngtkana) <a href="https://twitter.com/ngtkana/status/1305244786190737409?ref_src=twsrc%5Etfw">September 13, 2020</a></blockquote>

**Comment by kmyk** [comment]
メモ: https://github.com/kenkoooo/cargo-concat by @kenkoooo

**Comment by qryxip** [comment]
[cargo-equip](https://github.com/qryxip/cargo-equip)、結局[ngtkana/procon-bundler](https://github.com/ngtkana/procon-bundler)のようにライブラリを小さなクレートに分割する方式でいきました。

というのもRustのコンパイル単位はクレートなので「モジュール同士の依存関係」というものを考えようとした時点で辛くなります。`lib`クレート → `lib`クレートの依存はJSONのデータから連結成分を求めるだけですし、`bin`クレート → `lib`クレートも(私がcollaboratorをやっている)[cargo-udeps](https://github.com/est31/cargo-udeps)で列挙できます。[ralgo](https://github.com/MiSawa/ralgo)と同じく`save-analysis`を使ってますが、こちらはRLSは使わずにJSON内の`lib.name`をそのまま読むだけです。

懸念であった「ライブラリ同士の名前解決」はextern preludeからの解決を制約で禁じて`extern crate`でマウントしてそこを処理するという形で、「マクロの名前解決」は`$crate`を置き換え、`#[macro_export]`するものは上手い位置でre-exportするという形で解決できました。

この方針であれば`list_dependencies`を列挙するのにRustのコードを書く必要はなくなり、このような簡単なコードですべてが賄えます。(bundleがどうなるかはcargo-equipのREADMEから)

<https://github.com/qryxip/oj-verify-playground/blob/master/.verify-helper/oj-verify-rust.py>
<https://qryxip.github.io/oj-verify-playground>

問題は競プロライブラリをこのように小さなクレートに分割している人が今現在は皆無であることですね... [rust-lang-ja/ac-library-rs](https://github.com/rust-lang-ja/ac-library-rs)もモジュールで区切られた大きな単一のクレートです。cargo-equip用にはこのようなものを用意して対応しましたが...

[qryxip/ac-library-rs-parted](https://github.com/qryxip/ac-library-rs-parted) (oj-verify-playgroundでも使ってます)

あと一応現段階でのバンドルツール5つを比較してみました。誤りがあるかもしれませんが。

- [shino16/cargo-auto-bundle](https://github.com/shino16/cargo-auto-bundle) ![](https://img.shields.io/github/stars/shino16/cargo-auto-bundle?style=social) ![](https://img.shields.io/github/last-commit/shino16/cargo-auto-bundle) ![](https://img.shields.io/github/commit-activity/y/shino16/cargo-auto-bundle)

    1. **一つの大きなクレートからモジュールを抜き出してバンドルする**。
    2. **ライブラリ同士の依存に対応していないように見え、かつ難しそう。**
    3. `#[macro_export]`に対応していないように見える?
    4. **提出可能なソースコードを出力する**。
    5. `use crate::..`という形式のimportしか追わない。

- [kenkoooo/cargo-concat](https://github.com/kenkoooo/cargo-concat) ![](https://img.shields.io/github/stars/kenkoooo/cargo-concat?style=social) ![](https://img.shields.io/github/last-commit/kenkoooo/cargo-concat) ![](https://img.shields.io/github/commit-activity/y/kenkoooo/cargo-concat)

    1. 一つ以上のクレートをバンドルする。使わなさそうな部分の削除は行わず、すべてをそのまま出力する。
    2. ライブラリ同士の依存に対応していが、TODOリストに入っている。
    3. **`#[macro_export]`に対応していない**。
    4. **提出可能なソースコードを出力する**。
    5. ii., iii.と絶対パスが使用できないことを除けば制約は特に無い。

- [qryxip/cargo-equip](https://github.com/qryxip/cargo-equip) ![](https://img.shields.io/github/stars/qryxip/cargo-equip?style=social) ![](https://img.shields.io/github/last-commit/qryxip/cargo-equip) ![](https://img.shields.io/github/commit-activity/y/qryxip/cargo-equip)

    1. **多数の小さなクレートをバンドルする**。
    2. **ライブラリ同士の依存に対応**。extern preludeからの解決を禁じ、`extern crate`でマウントした場所を操作する。
    3. **`#[macro_export]`に対応**。
    4. **提出可能なソースコードを出力する**。というより競プロツールと組み合わせてバンドル → 提出をエディタ/ターミナルからワンアクションで行うことを想定している。エディタのバッファに展開することは想定していない。
    5. ライブラリ側に課す制約は大きい。独特な書き方を強いる。

- [kuretchi/cargo-simple-bundler](https://github.com/kuretchi/cargo-simple-bundler) ![](https://img.shields.io/github/stars/kuretchi/cargo-simple-bundler?style=social) ![](https://img.shields.io/github/last-commit/kuretchi/cargo-simple-bundler) ![](https://img.shields.io/github/commit-activity/y/kuretchi/cargo-simple-bundler)

    1. **一つの大きなクレートからモジュールを抜き出してバンドルする**。
    2. **ライブラリ同士の依存に対応していないように見え、かつ難しそう。**
    3. **`#[macro_export]`に対応**。
    4. **提出可能なソースコードを出力しない**。エディタのバッファに追記する方式であり、元のコードと合わせると提出可能な形になる。ただ使い方がよくわからない。まずライブラリを使ったコードを書き上げてから実行するようだが、`[dependencies]`にライブラリを加えた通常の開発環境であればエディタ上では"ambiguous name"というようなエラーで真っ赤になり、手でいくつか修正する必要になるはず。シンタックスハイライトだけ有効にしたプレーンなテキストエディタを想定している?
    5. モジュールの追跡は上手くやっているように見える。ただインラインモジュールやリネーム等が未対応。

- [ngtkana/procon-bundler](https://github.com/ngtkana/procon-bundler) ![](https://img.shields.io/github/stars/ngtkana/procon-bundler?style=social) ![](https://img.shields.io/github/last-commit/ngtkana/procon-bundler) ![](https://img.shields.io/github/commit-activity/y/ngtkana/procon-bundler)

    [本人が使用している動画](https://www.youtube.com/watch?v=nOn82Q0e1Co)

    1. **多数の小さなクレートをバンドルする**。ライブラリ一つ一つに対して実行する。
    2. **ライブラリ同士の依存に対応**。[展開するときに`s/another_lib::/crate::$0`を実行する](https://github.com/ngtkana/procon-bundler/blob/1c65a504bea4a70e4ca95b1f109f70d175a31fc0/src/bundle.rs#L190-L202)。
    3. **`#[macro_export]`に対応していない**。
    4. **提出可能なソースコードを出力しない**。エディタのバッファにライブラリを一つ一つ追記する方式。
    5. ソースコードもTOMLもパースせずにすべてをregexで捻じ伏せるという力強い方式。それでいてキッチリ動く。不味いケースがいくつかありそうではあるがiv.の形式から踏んだとしてもその場の損失は少なさそう。

**Comment by kmyk** [comment]
ところでいまさらだけど、Rust の作法的に最も正しいのは `oj-verify` を使うことでなくて `#![verify("https://judge.yosupo.jp/problem/unionfind")]` みたいな attribute を使って `cargo` に組み込む方針なはずなんですよね。これについては @ngtkana が詳しいはずだし、放っておけば作ってくれるはず。

**Comment by qryxip** [comment]
cargo subcommandにするのなら[Cargo.toml内の`package.metadata`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table)の方がいいんじゃないかと。作法的にも。

というより[cargo-compete](https://github.com/qryxip/cargo-compete/blob/master/README-ja.md) (snowchainsのコア部分を流用したRust専用競プロツール)が既にそれっぽいですね。Dropboxからのダウンロード機能を備えているので(snowchainsのと共用)今のままでもAtCoderの問題のverifyに使える...?

```toml
[package.metadata.cargo-compete.bin]
a = { name = "arc107-a", problem = { platform = "atcoder", contest = "arc107", index = "A", url = "https://atcoder.jp/contests/arc107/tasks/arc107_a" } }
b = { name = "arc107-b", problem = { platform = "atcoder", contest = "arc107", index = "B", url = "https://atcoder.jp/contests/arc107/tasks/arc107_b" } }
c = { name = "arc107-c", problem = { platform = "atcoder", contest = "arc107", index = "C", url = "https://atcoder.jp/contests/arc107/tasks/arc107_c" } }
d = { name = "arc107-d", problem = { platform = "atcoder", contest = "arc107", index = "D", url = "https://atcoder.jp/contests/arc107/tasks/arc107_d" } }
e = { name = "arc107-e", problem = { platform = "atcoder", contest = "arc107", index = "E", url = "https://atcoder.jp/contests/arc107/tasks/arc107_e" } }
f = { name = "arc107-f", problem = { platform = "atcoder", contest = "arc107", index = "F", url = "https://atcoder.jp/contests/arc107/tasks/arc107_f" } }
```

**Comment by shino16** [comment]
今はすべてクレートに分割する方針なのでしょうか。自分もよくわかってないですが、こちらは大丈夫ですか？

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">Rust で modint crate と polynomial crate があって相互に参照したいんですけど，普通にやると error: cyclic package dependency で怒られます．どうするのが美しい設計でしょう？</p>&mdash; たいやき🥐 (@3SAT_IS_IN_P) <a href="https://twitter.com/3SAT_IS_IN_P/status/1323856762106118144?ref_src=twsrc%5Etfw">November 4, 2020</a></blockquote>

**Comment by qryxip** [comment]
見栄えを良くする案:


```console
.
├── Cargo.toml
├── crates
│   ├── manifests
│   │   ├── my-complib-a
│   │   │   └── Cargo.toml
│   │   ├── my-complib-b
│   │   │   └── Cargo.toml
│   │   └── my-complib-c
│   │       └── Cargo.toml
│   └── src
│       ├── a.rs
│       ├── b.rs
│       └── c.rs
└── src
    └── lib.rs

7 directories, 8 files
```

```toml
# Cargo.toml

[workspace]

[package]
name = "my-complib"
version = "0.0.0"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
my-complib-a = { path = "./crates/manifests/my-complib-a" }
my-complib-b = { path = "./crates/manifests/my-complib-b" }
my-complib-c = { path = "./crates/manifests/my-complib-c" }
```

```rust
// src/lib.rs

pub mod a {
    //! A re-export of `my-complib-a`.
    pub use a::*;
}

pub mod b {
    //! A re-export of `my-complib-b`.
    pub use b::*;
}

pub mod c {
    //! A re-export of `my-complib-c`.
    pub use c::*;
}
```

```toml
# crates/manifests/my-complib-a/Cargo.toml

[package]
name = "my-complib-a"
version = "0.0.0"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"
publish = false

[lib]
name = "a"
path = "../../src/a.rs"

[dependencies]
my-complib-b = { path = "../my-complib-b" }
my-complib-c = { path = "../my-complib-c" }
```

```rust
// src/a.rs

use b::B;
use c::C;

/// A.
pub struct A(B, C);
```

![Screenshot3](https://user-images.githubusercontent.com/14125495/99243613-44144b80-2844-11eb-8763-98f5d2d7af00.png)
![Screenshot1](https://user-images.githubusercontent.com/14125495/99243620-470f3c00-2844-11eb-8148-bb501ac4800b.png)
![Screenshot2](https://user-images.githubusercontent.com/14125495/99243624-49719600-2844-11eb-94af-780795b87775.png)
