### ISSUE TITLE
Python 対応

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/verification-helper#114]
親 issue: #116

ライブラリ整備勢はたいてい C++ な気がするが、まあユーザ数的には多いしやる気のある人がいれば

**Comment by kmyk** [comment]
https://github.com/maspypy/compro_library (@maspypy)
https://github.com/knuu/contest_library (@knuu)

**Comment by kmyk** [comment]
Python の依存性解析ツールは [google/pytype](https://github.com/google/pytype) が内部で使ってる [google/importlab](https://github.com/google/importlab) を module として使うのがよさそう。
次点として [PyCQA/pylint](https://github.com/PyCQA/pylint) のおまけで付いてくる `pyreverse` があって、そう悪くもなさそうだけど CSV 出力とかないぽいし適切ではなさそう。

**Comment by kmyk** [comment]
@knuu さんが実装を試みてる気配があってうれしい https://github.com/knuu/online-judge-verify-helper/commits/features/add_python_lang

**Comment by kmyk** [comment]
@knuu 進捗どうですか？

**Comment by knuu** [comment]
ちょっと色々重なっていて 2 月末から進んでおらず，今もちょっと厳しいので再来週末になら進められそうかなという感じです．進捗状況としては，実装と既存レポジトリでのテストは終わっていて，あとは新規レポジトリを作ってそこに push したときを念の為に試したら pull request を出そうかと思っていました．

**Comment by kmyk** [comment]
ほぼ完成してたのか。ありがたい。
実装と既存レポジトリでのテストは終わっているならプルリクは出してもらって大丈夫です。

**Comment by knuu** [comment]
了解です．ただこれ 1 ヶ月以上前の記憶を元に話しているので，一応確認した上でプルリクを出そうと思っています．

**Comment by kmyk** [comment]
注意として、1か月以上前ということなら、こちらの最近の更新との merge 作業が発生するかもしれません。
影響のありそうな修正は次のふたつです。

- https://github.com/kmyk/online-judge-verify-helper/pull/200: 言語回りのクラスを `Language` と `LanguageEnvironment` に分けた。(「CPython と PyPy の両方でテスト」みたいなことができるようになりました)
- https://github.com/kmyk/online-judge-verify-helper/pull/220: 属性の指定方法の標準を `# verify-helper: KEY value` にした。

さっき別の用事で書いたマニュアル https://github.com/kmyk/online-judge-verify-helper/issues/116#issuecomment-610398056 も役に立つかもしれません。

すみませんが conflict してたら対応よろしくお願いします。

**Comment by kmyk** [comment]
@knuu これどうなりましたか
とりあえず conflict したままでいいので pull request にしてもらえるとたすかります

**Comment by knuu** [comment]
対応できてなくて申し訳無いです．いくつか制約はありますが，Language と LanguageEnvironment への分割などに対応して pull request を出しました．
