### ISSUE TITLE
C++ 以外の主要な言語にも組み込みで対応

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/verification-helper#116]
設定ファイルでの対応 (#73) はしたけど、設定なしで動く方がうれしいのは明らか。
言語ごとに対応するとメンテがたいへん (例: atcoder-tools) なんだけど、verify helper の場合はユーザのライブラリという形で CI が走るので比較的ましのはず。

-   [x] #113 Rust
-   [x] #114 Python
-   [ ] #115 C# / F#
-   [x] #119 Java
-   [x] #222 Nim
-   [x] #297 Go

(この他の言語であっても需要があり実装してくれる人がいれば issue 立ててください)

**Comment by kmyk** [comment]
何をすればよいか: 言語ごとに `Language` class を実装する。つまり以下を書く

-   `compile`: ファイルパスが与えられ、コンパイルする
-   `get_execute_command`: ファイルパスが与えられ、そのコンパイル結果に対する実行コマンドを返す
-   `list_attributes`: ファイルパスが与えられ、設定情報 (提出先問題URL, 許容誤差, etc.) を返す
-   `list_dependencies`: ファイルパスが与えられ、そのファイルが依存しているファイルの一覧を返す
-   `bundle`: (optional) ファイルパスが与えられ、そのファイルを単一ファイルにまとめて AtCoder とかに提出できるようにする

https://github.com/kmyk/online-judge-verify-helper/blob/1ca9500f6f2361bf49050f78250c05ca0bffe6cf/onlinejudge_verify/languages.py#L17-L36

**Comment by kmyk** [comment]
`list_attributes` (設定情報の辞書を返す) だけは設計が自明でないんですが、うまくやってください。
実用的には「コンパイラが clang++ でかつ ulimit に失敗している場合のみ実行をスキップしたい」などの単純な条件分岐を含む設定が可能な仕様にする必要があります。

**Comment by key-moon** [comment]
多言語対応する場合、`language.py`の中に全言語について詰め込むと可読性とか競合とかがあまりうれしくなさそうなので、`language`ディレクトリを作るなどして基底クラスと/C++クラスのファイルを分離してほしいです。

**Comment by kmyk** [comment]
分かる。同じ抽象クラスと継承関係にあるだけの無関係で独立なクラスが1ファイルに入ってるのはよくない。論理的凝集ってやつですね。
しかしいま忙しいのですぐには実装できません。あとでリファクタリングするのでひとまず好きに実装してください :bow:。`language` ディレクトリを作ってもらってもかまいません。

**Comment by kmyk** [comment]
環境を変えて複数回実行するための機能 (たとえば C++ なら `g++` と `clang++` の場合を両方試したい) はいまのところ C++ 専用になってしまっていますが、必要な言語があれば修正します

**Comment by kmyk** [comment]
つまり現状の設計は「プログラミング言語 (処理系や実行環境のことは考えない)」の概念と「プログラミング言語 + 固定された処理系や実行環境」の概念がごっちゃになってて不適切なのだね

**Comment by kmyk** [comment]
## 言語対応の追加のために何をすればよいか

### TL;DR

[onlinejudge_verify/languages/](https://github.com/kmyk/online-judge-verify-helper/tree/master/onlinejudge_verify/languages) の他のファイルを見て適当にやれ

### 丁寧な説明

1. [onlinejudge_verify/languages/](https://github.com/kmyk/online-judge-verify-helper/tree/master/onlinejudge_verify/languages) に新しい module を作る
1. 言語の実行環境に対応するクラス `LanguageEnvironment` を実装する
    - `compile()`: ファイルパスが与えられ、コンパイルする。
    -  `get_execute_command()`: ファイルパスが与えられ、そのコンパイル結果に対する実行コマンドを返す。
        - `oj test -c COMMAND` という形で利用されます。
    https://github.com/kmyk/online-judge-verify-helper/blob/be46613b9f63857a2c30d7f14ab107eec8b1dc51/onlinejudge_verify/languages/models.py#L9-L16
1. 言語 (の仕様) に対応するクラス `Language` を実装する
    - `list_dependencies()`: ファイルパスが与えられ、そのファイルが依存しているファイルの一覧を返す。
         -  `#include` とか `import` みたいなやつを解析します。処理系に付いてるその手の機能を呼び出してください。
         -  実行環境によって依存するファイルが変わる場合は和集合を取るのが理想ですが、最も標準的な環境の依存ファイルだけで妥協してもよい。
    - `bundle()`: (optional) ファイルパスが与えられ、そのファイルを単一ファイルにまとめて AtCoder とかに提出できるようにする。
        - `oj-bundle` の中身です。実装が難しいなら `raise NotImplementedError` でよい
   - `list_environments()`: 利用可能な実行環境の一覧を返す。
        - たとえば C++ なら基本的に `return [CPlusPlusLanguageEnvironment(CXX='g++'), CPlusPlusLanguageEnvironment(CXX='clang++')]` みたいになりますが、`g++` はインストールされてるけど `clang++` はインストールされてないといった場合に注意してください。

    https://github.com/kmyk/online-judge-verify-helper/blob/be46613b9f63857a2c30d7f14ab107eec8b1dc51/onlinejudge_verify/languages/models.py#L19-L36
1. 作ったクラスが読み込まれるように設定する。次のあたりに追加
    https://github.com/kmyk/online-judge-verify-helper/blob/e0f3c547985e791402a9d951ea56480cc97ea9a2/onlinejudge_verify/languages/__init__.py#L21-L23

**Comment by kmyk** [comment]
もうほぼ全部終わったと思います
