### ISSUE TITLE
C#/F# scriptへの対応

### ISSUE THREAD

**Issue by key-moon** [online-judge-tools/verification-helper#117]
#115 より

やること:
- [x] 実行方法の仕様確定/実装
- [x] 依存関係の解決の仕様確定/実装
- [x] [list_attributes](https://github.com/kmyk/online-judge-verify-helper/blob/1ca9500f6f2361bf49050f78250c05ca0bffe6cf/onlinejudge_verify/languages.py#L76-L78)で返す"属性"を何にするかの確定/実装(verifyファイル/問題の指定に使われる)
- [ ] doxygenのタグ確定/実装

**Comment by key-moon** [comment]
実行方法/依存関係については議論の余地がが殆どなさそう。(C++と同じく、ファイルごとの実行/依存関係の確立ができるため?)

- [filipw/dotnet-script](https://github.com/filipw/dotnet-script)を用いて、拡張子`csx`/`fsx`のファイルについて実行する。(コンパイルはなし)
- 依存関係は`#load`ディレクティブを用いて解決する。

**Comment by key-moon** [comment]
`dotnet script`からプリプロセス後のファイルを得る方法がない。
ライブラリを用いてC#で書いてpublishして…でも良いが、C#のプリプロセッサ ディレクティブは簡素なのでプリプロセスをPython上で十分実装できる。

pragmaとloadのファイルリストが一緒に求められるので一回で済ませたい 定義されているシンボル/pragma/依存しているファイル を返す関数を作っても良いかも
define状況によって結果が変わりうるので効率的なキャッシュはできなさそうだが、大体の場合何もdefineされていないのでキャッシュしたいのも事実。空かで呼び分けて空の関数だけキャッシュ…が現実的か。
本質的なボトルネックはネットワークIOなので、そこまで気にしなくていいかも。

**Comment by kmyk** [comment]
「pragmaと依存関係リストが一緒に求められるので一回で済ませたい」よさそう。

速度は気にしなくてよいです。ファイル数 N とひとつあたりの平均依存ファイル数 D と平均バイト数 S に対し O(N * D * S) ぐらいの計算量ですが、これは多めに見て N = 100, D = 20, S = 10000 なので適切なキャッシュをすれば数秒以下で間に合います。

**Comment by kmyk** [comment]
@key-moon が実装してくれました :tada:

---

残りやること:

- [ ] ドキュメントを書く
- [ ] 1ファイルにまとめるやつ
- [ ] コメントの記法についていい感じにする

## ドキュメントを書く

これ必須です。

1.  詳しいドキュメントを書く
    - 「`#load` が読み込まれます」とかそういうやつ
    -  実際の運用例として [key-moon/Library](https://github.com/key-moon/Library)  へのリンクを貼っておくと親切そう
    - <https://kmyk.github.io/online-judge-verify-helper/document.html> <https://kmyk.github.io/online-judge-verify-helper/document.ja.html> に書く (<https://github.com/kmyk/online-judge-verify-helper/blob/master/.verify-helper/docs/static/document.md>, <https://github.com/kmyk/online-judge-verify-helper/blob/master/.verify-helper/docs/static/document.ja.md> を編集する)
2. サンプルが不親切すぎるので増やす
    - 「segment tree + その利用例」ぐらいの複雑さはほしい
    -  [key-moon/Library](https://github.com/key-moon/Library) で実際にしばらく使ってみてそこからコピペでよさそう
    - 現状: https://github.com/kmyk/online-judge-verify-helper/blob/8dbd10794e51795294b2cd3431ddc1a0c700d060/examples/CSharpScript/csharpscript.test.csx

## 1ファイルにまとめるやつ

実装するだけなので、この機能がほしい人がいたら書いてください

## コメントの記法についていい感じにする

現状のドキュメント生成部分のコードはかなりしんどいので先にリファクタリング (#118 #46 ) を終わらせないとたぶん無理。個人的には見なかったことにしたい

**Comment by key-moon** [comment]
> ドキュメントを書く

やります。(`readme`の若干不整合がある部分も簡潔性を崩さない程度に修正しておきます。英訳は英語力に自信がないためお願いしたいです…)

> コメントの記法について

コメントのフォーマットはXMLドキュメントコメントで良いと思うんですが、実装が現状だと沼っぽいのでリファクタリングが終わり次第やります。

> F# script

実行環境としては`dotnet fsi`を使うと良さそう?(あまり選択肢はなさそうです)
`pragma`に該当するものがないので、何らかの形でオレオレ記法を定めてあげるしかなさそう。一番マシなのはドキュメントコメントの内部で定義すること?

**Comment by kmyk** [comment]
> やります。(readmeの若干不整合がある部分も簡潔性を崩さない程度に修正しておきます。英訳は英語力に自信がないためお願いしたいです…)

ありがとう。
英語が難しいなら、日本語のだけ書いてプルリクくれれば翻訳します (私も自身ないですが…)

**Comment by kmyk** [comment]
C# script のこの issue はもう閉じていいでしょ
