### ISSUE TITLE
ドキュメント生成機能部分において、ソースコードの分析とHTMLの生成を分離する

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/verification-helper#118]
#116 をするので重要。それぞれの言語の標準の形式が使えると IDE の恩恵を受けられるようになるため。
実質的な内容は #46 とほぼ同じなんだけど、動機が違うので念のためもういちど issue を立てておきました。

**Comment by kmyk** [comment]
このリファクタリングは #117 とかにも必要でかなり優先度高いのですが、私はやりません。なぜならば、やりたくないからです。元々私の書いたコードじゃないのでふつうにしんどい。
そして、 `onlinejudge_verify/docs.py` が私が書いたコードでないということは、私以外の誰がリファクタリングをしても条件は同じということです。@beet-aizu @tsutaj @key-moon たすけて

**Comment by key-moon** [comment]
C#の方を優先しますが、終わってなければやります(終わっていてほしい)

**Comment by kmyk** [comment]
じゃあもし F# の対応もされたら泣きながら私がリファクタリングやります (C# は書かないけど F# は書くので)

**Comment by kmyk** [comment]
メモ: http://jekyllrb-ja.github.io/docs/datafiles/
