### ISSUE TITLE
yukicoderのドキュメントを書く

### ISSUE THREAD

**Issue by beet-aizu** [online-judge-tools/verification-helper#170]
多分今エスパーしないと動かない

**Comment by kmyk** [comment]
> 環境変数 YUKICODER_TOKEN の設定が必要です。ヘルプ - yukicoder の「ログインしてないと使えない機能をAPIとして使いたい」の節や 暗号化されたシークレットの作成と利用 - GitHub ヘルプ 参考にして設定してください。

これが書かれてるし十分だと思う。
本当にそうか？ いや、まあわかるやろ。close
