### ISSUE TITLE
rename

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/verification-helper#225]
"verify helper" って和製英語感あるよねって指摘されてなんだか気持ち悪くなってきてしまっています。海外勢への布教を考えるとなんとなく良くない気がしています。しかし無闇に名前を変えるのもまたよくない。
ちょうどレポジトリの名前を変更する機会 (*) があるんですが、これどうしましょうか？
cc: @beet-aizu @tsutaj @key-moon @sash2104 @southball @rsk0315

---

(* online-judge-tools まわりをまとめたひとつの GitHub organization を作ろうと思っています。プロジェクト間の関係のユーザにとっての分かりやすさを増すことと、バス係数の増加が目的です。レポジトリが移動するのでついでにレポジトリの名前を変えられます。pip でインストールするときとかのパッケージ名は変わりません)

**Comment by kmyk** [comment]
雑に投票式していくか。ユーザでなくても誰でも好きに押してください

**Comment by southball** [comment]
プロジェクト URL はどうしても変わるから、もし GitHub organization に移動するなら名前を変えてもいいと思います（今の名前よりいいのを考えられたら）。

`competitive-programming`、`template`、`online-judge`、`verify-helper`または`verifier`などのキーワードから新しい名前を作りますか、それともキーワードを含まれていない、覚えやすい (?) 名前を作りますか？

**Comment by kmyk** [comment]
変更先の名前のことはあまり考えてませんでした (うっかり)
基本的には最小限の変更で `verification-helper` にするのかなと思っていましたが、よい名前があれば他のでもよいと思っています。

GitHub organization は `online-judge-tools` で取ることになると思います。なので選択肢の例は次のようになります。好きなやつをコメントしていってね

-   `online-judge-tools/beeeeeeeetsutaj` (キーワードを組み合わせるのでなく、まったく新しい名前を考える場合の例)
-   `online-judge-tools/online-judge-verify-helper` (まったくそのまま)
-   `online-judge-tools/verify-helper` (`online-judge-` の重複を取る)
-   `online-judge-tools/verification-helper` (`verify` を名詞に直す)
-   `online-judge-tools/verifier` (`helper` を削除)
-   `online-judge-tools/library-verifier` (`library-` を追加する場合)
-   `online-judge-tools/library-documenter` (verify する部分よりもドキュメント生成の部分を本質だと考える場合 1)
-   `online-judge-tools/document-generator` (verify する部分よりもドキュメント生成の部分を本質だと考える場合 2)
-   `online-judge-tools/library-helper` (verify する部分よりもライブラリの整備を助ける部分が本質だと考える場合) (部分文字列に `library` を入れると Library Checker と紛らわしくてよくないかも？)
-   `online-judge-tools/online-judge-library-helper` (`online-judge-` をやっぱり残す場合)

(名前を大きく変えると (例: `verify` を消して `document` にするなど) プロジェクトの方向性も変わりがちですが、そこは利用方法については私より詳しいだろう @beet-aizu @noshi91 @ei1333 あたりの判断を仰ぎたい)

**Comment by noshi91** [comment]
- 名前について
verification-helper
library-helper
に一票です
- プロジェクトの方向性が変わる場合について
既存の機能が大幅に削除されるのでない限り、勝手に機能の subset を利用するだけなので私は気にならないと思っています

**Comment by sash2104** [comment]
verifyの部分が本質で他 (bundleやドキュメント生成) はそのための補助的な機能だと思っていたので、`verification-helper` に一票です

**Comment by tsutaj** [comment]
verify 主体のプロジェクトだと捉えているので、 `verification-helper` もしくは `library-verifier` が良いかなと考えています (verify という単語は残したい派です)

**Comment by beet-aizu** [comment]
verify-helper のままがいいので理由を考えていたんですが特に思いつきませんでした

**Comment by beet-aizu** [comment]
ちょっと変な名前の方が検索しやすさは上がると思ったんですが、verification helperで検索すると現状でも一番上にくるため、はい

**Comment by rsk0315** [comment]
verify（語形は文脈に合わせて）と helper はあるとうれしいかなと思っている派です（このツール自体がライブラリを verify しているわけではなくて help している感覚があるため）
`/verification-helper` に一票入れます（えーでもちょっと呼びにくいかもだよね）

**Comment by kmyk** [comment]
だいたいみんな `verification-helper` なので、`verification-helper` でいきます。

(`verify-helper` のままがいい人がいるのは分かりますが (こっちの方がなんとなく呼びやすいし)、どちらか一方しか採用できないので申し訳ないが諦めてください)

**Comment by kmyk** [comment]
rename された
