### ISSUE TITLE
Run tests on Windows

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/verification-helper#235]
たとえば #234 みたいなことがあるので、verification-helper 本体が Windows や Mac OS で動くことのテストを書いておく必要がある

**Comment by tsutaj** [comment]
これに関連する話かもしれないのですが、`resource` モジュールは UNIX にしかないようで、`onlinejudge_verify/verify.py` においてこれを import しているので、Windows 環境で動かないようです。

waku くんが困っているので気づきました (https://twitter.com/wakuwinmail/status/1259022731397361664)

クロスプラットフォームであるはずの `psutil` などで代用できないか考えているところです

**Comment by kmyk** [comment]
`resource` の問題は知りませんでした。
`resource` はスタックサイズを増やすためのものであり、必須ではありません。[`platform.system`](https://docs.python.org/3/library/platform.html#platform.system) などを呼んで Windows だった場合は処理をスキップするのがよさそうです。

@tsutaj この `resource` の問題の修正を任せたいのですが、よいですか？

**Comment by tsutaj** [comment]
大丈夫です、対応します！

**Comment by kmyk** [comment]
ありがとうございます

**Comment by tsutaj** [comment]
@kmyk こちらの環境の Windows 上で正しく動くかのテストに時間がかかりそう (仮想環境などをこれから入れるため) で、本日中には対応できると思いますが数十分でどうにかするのは難しいです。

WSL などを入れていない素の Windows で動かない旨を書いておいて欲しいとの要望をいただいた (https://twitter.com/wakuwinmail/status/1259036000640106496?s=21) ので、こちらの対応をお願いしてもよろしいですか？ (私がやっても良いのですが、そのためだけに PR 送るのは少々仰々しいので)

**Comment by kmyk** [comment]
はい。ドキュメントの修正はやっておきます。

**Comment by kmyk** [comment]
いや、本日中には対応できるならこのままでよくないですか？ だめかな？

**Comment by tsutaj** [comment]
たぶんすぐ直るのでそのままでもいいかもしれないですね・・・？

`resource` 以外にももし問題があればつらくて、そうなったらお願いするかもしれないです。

**Comment by kmyk** [comment]
> `resource` 以外にももし問題があればつらくて、そうなったらお願いするかもしれないです。

了解です

**Comment by tsutaj** [comment]
Windows でためしに走らせてみたら Cygwin だとうまくいっちゃいました・・・ (resource がないと怒られることもない)
ほかの環境も試してみます

**Comment by kmyk** [comment]
https://www.python.org/downloads/windows/ からインストーラーの `.exe` を拾ってきてインストールしたりする必要があるはずです。

Cygwin は Windows 上に Linux 環境を再現するためのツールなので、再現がうまくできちゃってるのだと思います。MinGW とかも同様です。(ところで、Cygwin 上なら動くというのはそれはそれで有益情報なんですよね)

**Comment by tsutaj** [comment]
ありがとうございます、インストールして試してみます

**Comment by kmyk** [comment]
開発の初期に「Library Checker は Windows に未対応らしいから verification helper も Windows 未対応でええやろｗ」をしていた記憶が蘇えってきました。すっかり忘れてた。ごめんなさい……

**Comment by tsutaj** [comment]
😢

**Comment by kmyk** [comment]
macOS は macOS で難しいことが分かったので issue を分けます
https://github.com/online-judge-tools/verification-helper/issues/258

**Comment by kmyk** [comment]
@wakuwinmail GitHub Actions 上では Windows 対応できました。実際にできてるかの確認のため、`$ pip3 install git+https://github.com/online-judge-tools/verification-helper` で開発版をインストールしてしばらく使ってみてください。よさそうならバージョン更新します

**Comment by kmyk** [comment]
返答ないけどまあええやろ
