### ISSUE TITLE
C++のヘッダファイルとして.hが使えないことを明記して欲しい

### ISSUE THREAD

**Issue by yosupo06** [online-judge-tools/verification-helper#248]
現状hppにしか対応していないと思うのですが、これをhに拡張するか、もしくは警告を出すべきではという提案です

- hとhppについてあまり深く考えずに使っている人がいる(ex. 自分): もしこれが自分だけの場合、このissueはここまでです

- hを使ったことが理由であることを判断するのが著しく困難: 以下のようなエラーが出るはずで、ここからエラーの理由を推測するのは無理だと考えます

```
  File "/usr/local/lib/python3.7/site-packages/onlinejudge_verify/docs.py", line 282, in write_contents
    raise FileNotFoundError('{} seems not to exist in path_to_verification'.format(depends))
FileNotFoundError: /Users/yosupo/Programs/Sand/base.h seems not to exist in path_to_verification
```

- 多分この仕様についてドキュメントで言及していない

**Comment by kmyk** [comment]
これは修正しておいた方がよさそう。特にエラーが `FileNotFoundError` になるのはひどい。
(競プロ界隈ならみんな何も考えず `.cpp` `.hpp` してるでしょと思って放置していました :bow:)


`docs.py` を触る必要があるかもでしんどいので、どう対応するかはすこし考えます。

メモ：

- C++ の拡張子としては `.cpp` `.hpp` の他に `.cc` `.cxx` `.c++` `.c` `.C` `.hh` `.hxx` `.h++` `.h` `.H` が使われている
- C# script から依存する C# の `.cs` にもなにか警告があった方がよさそう

**Comment by kmyk** [comment]
たぶん以下の 3 つの異なる問題に分割できる

1. `.hpp` や `.cpp` 以外のファイル (例: `.h`, `.txt`) は「ドキュメントを生成しない」「テストの対象として認識されない」だけでよいはず。コードのファイルがコード以外のファイル (辞書.txt とか) に依存するのはよくある状況であり、例外を発生させて落とすべきものではない (仕様あるいはコードのバグ)
1. C++ の拡張子が何であるかは自明でないのに、これについて記述がない (ドキュメントのバグ)
1. もし未対応のまま残すなら、`.h` `.cs` などありがちなものについては警告を出すべき (バグではないが不親切)

**Comment by kmyk** [comment]
これ忘れてたのですが、いまドキュメント更新しました。
また、ドキュメント生成パートの大改修の際に、ライブラリとして認識されてないファイルへの依存があったら警告とともに無視されるようになっています。なので現在ではすべて解決されています。
