### ISSUE TITLE
誤差ジャッジが通らない

### ISSUE THREAD

**Issue by knagakura** [online-judge-tools/verification-helper#253]
http://judge.u-aizu.ac.jp/onlinejudge/description.jsp?id=CGL_1_A
この問題で、提出はACしますが、以下のようにverifyでWAがでます。
誤差ジャッジの場合に何か設定する項目があるのでしょうか？
https://github.com/knagakura/procon_library/runs/658586500?check_suite_focus=true

**Comment by tsutaj** [comment]
https://online-judge-tools.github.io/verification-helper/document.ja.html の「利用可能な属性」に、`ERROR` という項目があります。
これは `#define PROBLEM` と同じように、例えば `#define ERROR "1e-6"` などと追加していただけると、所望の誤差でジャッジされますのでお試しください。

**Comment by knagakura** [comment]
ありがとうございます
