### ISSUE TITLE
@ignore が消えた

### ISSUE THREAD

**Issue by beet-aizu** [online-judge-tools/verification-helper#293]
ざっと読んだ感じそもそもサポートをやめている？わりと困ります

**Comment by kmyk** [comment]
使ってる人いなさそうだと思ってた。わりと困るのは分かる (このリポジトリで困ってる例: https://online-judge-tools.github.io/verification-helper/onlinejudge_verify/main.py) のでなんとかする予定はあります。
ソースコードに個別に `@ignore` していくのは筋が悪い (このリポジトリみたいな困り方に対応できない) と思うので http://jekyllrb-ja.github.io/docs/configuration/options/#:~:text=%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%84%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%88%E3%83%AA%E3%82%92%E5%A4%89%E6%8F%9B%E6%99%82%E3%81%AB%E9%99%A4%E5%A4%96%E3%81%99%E3%82%8B%E3%80%82 みたいな方向でやるつもりです

**Comment by beet-aizu** [comment]
#301
