### ISSUE TITLE
Go 対応

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/verification-helper#297]
sub-issue of #116 

とりあえず建てておく

**Comment by kmyk** [comment]
bundle してくれるツールを @monkukui が https://github.com/monkukui/gpcg として実装してる
依存関係解析をやってくれるのはなさそうだけど、bundle ができたらすでに解析できてるも同然なのでインターフェース次第か

**Comment by monkukui** [comment]
今のままでは全く使えなさそうですが，将来的に貢献できると嬉しいです．

**Comment by kmyk** [comment]
まだ機能不足はあると思うし、通常の Go の流儀と組合せて使いやすいかの検証とかもはできてないが、とりあえず対応はされているということで閉じておきます。
