### ISSUE TITLE
oj-bundle with multiple include path 

### ISSUE THREAD

**Issue by jellc** [online-judge-tools/verification-helper#298]
最後に '-I' で指定したパスのみがコンパイルオプションで include path として渡されています(例えば引数を ['-I', '/path/to/Library1', '-I', '/path/to/Library2'] と渡すと、Library1 にパスが通らず Library2 には通る)。
https://github.com/online-judge-tools/verification-helper/blob/a4eb22351146f273c925e749c62aa0d5ab8325ad/onlinejudge_bundle/main.py#L24

クラス 'Language' とその派生クラスのメソッド 'bundle' のシグニチャを変更する('basedir' の型を 'List[pathlib.Path]' にする)ことで対応しようと考えています。それによって生じると想定される不具合や、より良い対応などあれば教えて頂きたいです。

**Comment by kmyk** [comment]
自分のライブラリと [atcoder/ac-library](https://github.com/atcoder/ac-library) とを同時に使いたい、みたいな動機でしょうか。これができるようになってよろこぶ人は多そうで、対応やってくれるならありがたいです。

---

> クラス 'Language' とその派生クラスのメソッド 'bundle' のシグニチャを変更する('basedir' の型を 'List[pathlib.Path]' にする)ことで対応しようと考えています。それによって生じると想定される不具合や、より良い対応などあれば教えて頂きたいです。

「クラス 'Language' とその派生クラスのメソッド 'bundle' のシグニチャを変更する」のはよさそうです。しかし 'basedir' の型を 'List[pathlib.Path]'  にするのはすこし不具合がありそうで、`def bundle(self, path: pathlib.Path, *, basedir: pathlib.Path, options: Dict[str, Any]) -> bytes` という形にするのが無難かなと思います。

想定される不具合:

1. `basedir` という語は「`.verify-helper` や `.git` が置いてあるディレクトリ」の意味で使われています。これが複数になってしまうとたぶんいろいろ壊れます。
2. include path の概念は C++ に特有のものです。逆に C++ にはない要求が他の言語から出てくることも予想できます。抽象クラス `Language` の側を C++ 専用の形に修正してしまうと、他の言語を実装するときに混乱します。

その他の選択肢:

1. `def bundle(self, path: pathlib.Path, *, basedir: pathlib.Path, cplusplus_include_paths: List[pathlib.Path]) -> bytes` なら、変数名が `cplusplus_*` であればぎりぎり許されるし、いま bundle 機能に対応できてるのは C++ だけなのでたぶんセーフです
2. `CPlusPlusLanguage` のコンストラクタに引数を増やす選択肢も存在しますが、あまりきれいではなさそう。コンパイル時のオプションの管理や切り替えは `LanguageEnvironment` の側の役割なので
3. `cplusplus_bundle.py` の中で環境変数 `CPLUSPLUS_INCLUDE_PATH` を読みに行く実装も可能ですが、これは避けたいです。oj-bundle から呼ぶ分には困らないのですが、oj-verify から呼ぶときに複数の環境の切り替えのまわりで混乱するためです

**Comment by jellc** [comment]
ありがとうございます。設計の理解が不十分な提案で申し訳なかったです。 

> 「クラス 'Language' とその派生クラスのメソッド 'bundle' のシグニチャを変更する」のはよさそうです。しかし 'basedir' の型を 'List[pathlib.Path]' にするのはすこし不具合がありそうで、`def bundle(self, path: pathlib.Path, *, basedir: pathlib.Path, options: Dict[str, Any]) -> bytes` という形にするのが無難かなと思います。(`options: Dict[str, Any]` がきれいかと言われるとそうでもないので、実装していて良いものを思い付いたらそれを使ってもらってかまいません)

ある程度汎用性、柔軟性がありそうなこの形をとろうと思います。

> 想定される不具合:
> 
> 1. `basedir` という語は「`.verify-helper` や `.git` が置いてあるディレクトリ」の意味で使われています。これが複数になってしまうとたぶんいろいろ壊れます。

全ての特殊化を確認せずに言ってしまっていたのですが、 'other.py' を見てこれがマズそうなことに気づきました。意味論的にもおかしいですし、そもそも Not Implemented な言語を無視するのも将来性を考えるとおかしいですね、、

> 2. include path の概念は C++ に特有のものです。逆に C++ にはない要求が他の言語から出てくることも予想できます。抽象クラス `Language` の側を C++ 専用の形に修正してしまうと、他の言語を実装するときに混乱します。

 C++ 特有の概念だという認識を持っていませんでした。なるほど納得です。
