### ISSUE TITLE
Verified with の順番が不定

### ISSUE THREAD

**Issue by beet-aizu** [online-judge-tools/verification-helper#327]
ソートしたい
![Screenshot_2020-09-28 遅延伝播セグメント木](https://user-images.githubusercontent.com/20266375/94387899-74b20000-0186-11eb-9edf-fdfea91bb1a1.png)

**Comment by kmyk** [comment]
(1.)「依存関係を解析して Python の構造体にまとめる」(2.)「Python の構造体から JSON を生成する」(3.)「Markdown に埋め込まれた JSON あるいは YAML から HTML を生成する」という過程で最終的な出力が得られています。このどこかにソート処理を入れてください。どこを修正しても動くけど (2.) の部分である次を修正するのがよさそう？

https://github.com/online-judge-tools/verification-helper/blob/3c925240b9640742285e90013d0a961b7df46933/onlinejudge_verify/documentation/build.py#L65-L114
