### ISSUE TITLE
Bundlerがatcoder aclの場合は#include <>の形式でもexpandできるようにする。

### ISSUE THREAD

**Issue by kjnh10** [online-judge-tools/verification-helper#342]
@kjnh10 issue の作成ありがとうございます。
ところで、https://github.com/online-judge-tools/verification-helper/pull/336#issuecomment-717876056 のふたつのうち、前者は「仕様の修正の提案」であり、後者は「バグの報告」です。これらの異なる 2 種類のものをまとめて話すと面倒 (https://github.com/online-judge-tools/verification-helper/issues/340#issuecomment-719143873 でも「後者に関しては」などのような限定が必要になってる、"bug" などの label が貼りにくい) ので、この issue では後者についてのみ議論することにさせてください。

---

(後者について、) 手元で試すと再現しませんでした。以下のように、拡張子がないファイルについても適切に動作しているように見えます。
@kjnh10 バグを再現させるための具体的な手順を教えてもらえますか？

``` console
$ cat foo.cpp 
#include "bar"
world
$ cat bar
hello
$ oj-bundle foo.cpp > foo.bundled.cpp
INFO:onlinejudge_verify.config:config file loaded: .verify-helper/config.toml: {'languages': {'awk': {'compile': "bash -c 'echo hello > {tempdir}/hello'", 'execute': 'env AWKPATH={basedir} awk -f {path}', 'bundle': 'false', 'list_dependencies': 'sed \'s/^@include "\\(.*\\)"$/\\1/ ; t ; d\' {path}'}}}
WARNING:onlinejudge_verify.languages.list:config.toml: languages.awk: Adding new languages using `config.toml` is supported but not recommended. Please consider making pull requests for your languages, see https://github.com/kmyk/online-judge-verify-helper/issues/116
DEBUG:onlinejudge_verify.languages.cplusplus_bundle:foo.cpp: line 1: #include "bar"
g++: warning: /home/user/GitHub/online-judge-verify-helper/bar: linker input file unused because linking not done
$ cat foo.bundled.cpp 
#line 1 "bar"
hello
#line 2 "foo.cpp"
world
```

_Originally posted by @kmyk in https://github.com/online-judge-tools/verification-helper/issues/340#issuecomment-720441233_

## どのような状況でどのようなコマンドを実行したか (再現方法)
main.cpp
```
#include <atcoder/math>
```
としてoj-bundle main.cpp -I [path-to-ac-library]/ac-libraryを実行。

## 実際にはどう動くのか (実際の挙動)
atcoder/mathが展開されない。エラーにはならない。

## どう動いてほしいと思ってるのか (期待される挙動)  
atcoder/mathが展開される。aclが展開されてほしいかは状況によるのでoj-bundleにオプションを渡して選択させるのがよさそうです。

**Comment by kjnh10** [comment]
「前者」についてもissueをとりあえず立てておきます。

**Comment by kmyk** [comment]
@kjnh10 なにが問題であるのかについてもうすこし具体的に書いてほしいです。つまり、「どのような状況でどのようなコマンドを実行したか (再現方法) 」「実際にはどう動くのか (実際の挙動) 」「どう動いてほしいと思ってるのか (期待される挙動) 」の 3 つを

**Comment by kmyk** [comment]
(間違えて Close with comment ボタンを押してしまった)

**Comment by kmyk** [comment]
``` c++
#include <atcoder/math>
```

と書いて展開されないのは仕様です。ユーザは

``` c++
#include "atcoder/math"
```

と書くべきです。
この仕様の根拠は [DESIGN.md](https://github.com/online-judge-tools/verification-helper/blob/master/DESIGN.md) に説明があります。

> oj-bundle コマンドは #include "..." の形の include のみを展開し #include <...> の形の include は展開しない。この仕様は、#include <...> が「システムの標準のヘッダ」に使われることが意図されており、また #include "..." が「カレントディレクトリなどにある自作のヘッダ」に使われことが意図されている、という事情による。参考として、プリプロセッサの挙動についての説明は https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html にある。

---

@kjnh10 この仕様に対し AtCoder Library だけを例外扱いする理由がよく分かりません。

> aclが展開されてほしいかは状況によるのでoj-bundleにオプションを渡して選択させるのがよさそうです。

また、上のようにありますが、ユーザにとって、わざわざ新しいオプションを覚えて使うより単に `#include "atcoder/math"` と書いた方が楽だと思います。
「aclが展開されてほしいかは状況による」ということですが、ひとつのコードを AtCoder と Codeforces に提出し分ける機会はそうそうないはずです。自作ライブラリ内から AtCoder Library を利用している場合だけはそのような状況になるかもしれませんが、常に展開してしまう (ユーザには `#include "atcoder/math"` と書いてもらう) ようにすれば十分でしょう。

**Comment by kmyk** [comment]
この issue は重要なものには見えないので、とりあえず close しておきます。
私が何か見落としているなら指摘して再 open してください。

(でもそもそも最初の @kjnh10 さんの説明だと、こういう話ではなかった気がします。もし現在の https://github.com/online-judge-tools/verification-helper/issues/342#issue-735563841 に書かれている説明が間違っているのなら、新しく issue を建ててもう一度説明し直してほしいです)

**Comment by kjnh10** [comment]
#include "atcoder/math"は現状だと展開されません。

このファイル自体は展開されるのですがこの中身は
#include <atcoder/math.hpp>
となっており結局ここが展開されないので。

**Comment by kmyk** [comment]
@kjnh10 冒頭のコメント (https://github.com/online-judge-tools/verification-helper/issues/342#issue-735563841) に書かれているのは「`#include <atcoder/math>` が展開されない」であり、https://github.com/online-judge-tools/verification-helper/issues/342#issuecomment-724028490 で言っているのは「`#include "atcoder/math"` が実質的に展開されない」です。仕様についての説明 (https://github.com/online-judge-tools/verification-helper/issues/342#issuecomment-724024463) を読んでもらえば分かるように、これらは異なります。

「`#include "atcoder/math"` が実質的に展開されない」は直すべき重大な問題ですが、この issue で説明されている問題とは異なる問題であるので、新しく issue を建ててください。よろしくお願いします :bow:

**Comment by kjnh10** [comment]
expander.pyは#include <atcoder/....>を展開できるのでoj-bundleも同様の形式を扱えるようにした方がよいのでは？というのがこちらでissueを立てた当初の目的でした。

aclのdocumnet(例えばhttps://atcoder.github.io/ac-library/document_ja/dsu.html)では#include <atcoder/...>形式でincludeするように書かれていて、またexpander.pyでも展開できるのにoj-bundleで同じコードを展開しようとすると出来ないというのはある意味よくない気がしていましたので。

ただaclだけは<>でも展開出来て他のはしないとなるとそれはそれで混乱の元な気もするのでデメリットがある事も理解しています。

ですので@kmykさんの方でaclといえども#include <atcoder/....>形式は許容しがたい、ということであればこちらのissueはclosedで構いません。個人的には何らかの方法でoj-bundleが展開してくれるのであればそれで十分ですので、その場合は#include "atcoder/...."が展開されるようにするという新しいissueを作成して対応しようと思います。

もしaclだけは#include <>が展開されるのもよいということであればこのissueのままでよいのかなと思っています。

**Comment by kmyk** [comment]
@kjnh10 だいたい分かってきました。解決の方針についてはこちらでしばらく考えさせてください。関連する issue は後で私が建て直します。
具体的な方針がどうなるかは分かりませんが、とにかく「`oj-bundle` コマンドと AtCoder Library の連携がうまく行くようにするべきである」「現状は連携がうまく行っていない」とは思っていますので、申し訳ないですがしばらく待っていてください。
