### ISSUE TITLE
workflow for C# users fails due to disabled command "add-path"

### ISSUE THREAD

**Issue by rajyan** [online-judge-tools/verification-helper#349]
## Description

C#ユーザーの設定
https://github.com/online-judge-tools/verification-helper/blob/master/.github/workflows/verify.yml#L34
について

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
にある通り、
add-pathが見つかった脆弱性によってdeprecatedになって使えなくなっていて、C#ユーザーはこれが原因で落ちます。

https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
にあるように修正しようと考えています。

## Error log

https://github.com/rajyan/library/actions/runs/378426764

## Other notes

-   Will you try to create a pull request?
    -   yes

**Comment by kmyk** [comment]
報告ありがとうございます。落ちてまったく使えなくなるのはこまりますね。

**Comment by kmyk** [comment]
@key-moon 特に何かをしてほしいわけではないですが、とりあえず ping しておきます

**Comment by kmyk** [comment]
Haskell も壊れてたので
