### ISSUE TITLE
Docs の説明

### ISSUE THREAD

**Issue by tsutaj** [online-judge-tools/verification-helper#37]
自分が仕様を整理するためにもかいておきたい

**Comment by kmyk** [comment]
`.verify-helper/docs/static/hoge` に何か書くとそのまま gh-pages にコピーされるようになってる (こっそり追加した) のでこれを使って書くとよさそう (例: https://github.com/kmyk/online-judge-verify-helper/blob/master/.verify-helper/docs/static/installer.html → https://kmyk.github.io/online-judge-verify-helper/installer.html)。たぶん markdown も使えます

**Comment by kmyk** [comment]
すでに書き終わってるはず
