### ISSUE TITLE
oj-verifyがローカルで実行できない

### ISSUE THREAD

**Issue by Coki628** [online-judge-tools/verification-helper#405]
## Summary / 概要

oj verifyがローカルで実行できない

## Steps to reproduce / 再現方法

1.  Windowsのローカル環境でoj-verify run(allでも)を実行
2.  「FileNotFoundError: [WinError 2] 指定されたファイルが見つかりません。」といったエラーが出る。

environments:

-  Windows 10

## 想定される原因と対処方法

エラーを追ってみたところ、oj downloadする前の`sleep 2`の所で落ちていて、おそらくWindowsのcmdにsleepコマンドが存在しないのが原因かと思われます。
([https://github.com/online-judge-tools/verification-helper/blob/master/onlinejudge_verify/verify.py](url)の79行目)
試しに該当箇所`exec_command(['sleep', '2'])`をPythonの`time.sleep(2)`に置き換えてみたところ、問題なく動作しました。
この2秒止める処理をPython側ではなくOS側の処理でやっていることには何が理由があるのでしょうか？

## Other notes / その他

-   Will you try to create a pull request?
    -   yes

特に2秒止めるのをPython側でやることに全体として問題がないのであれば、該当箇所を修正したプルリクを出すことは、こちらで対応できるとは思います。

**Comment by kzrnm** [comment]
Pull request 作成済みです。 #400

**Comment by Coki628** [comment]
PR既に出してくださってたんですね！
気が付かず申し訳ありません。
ご対応ありがとうございました。
