### ISSUE TITLE
ドキュメントページにBundleボタンが出現せず、コードが2つ縦に並ぶ

### ISSUE THREAD

**Issue by Nafmo2** [online-judge-tools/verification-helper#413]
## Summary / 概要
github pagesのドキュメントページにBundleボタンが出現せず、コードが2つ縦に並ぶという状況に陥りました。

## Steps to reproduce / 再現方法

1.  インストールマニュアルの手順を一通り行う( https://online-judge-tools.github.io/verification-helper/installer.ja.html)
1.  Github ActionsでPushできるようにWorkflow permissionsを変更する
1.  [example.test.cpp](https://github.com/online-judge-tools/verification-helper/blob/master/example.test.cpp) のコードが2つ並んでいた

インストールマニュアルだけを行った別リポジトリでも同じ現象に遭遇したので、インストールマニュアルの手順だけで再現可能であるはずです。

environments:

-   version: online-judge-tools 11.5.1 (+ online-judge-api-client 10.10.1)
    - local で `bundle exec` をしたときはbundleボタンが表示されます。
    - GitHub pages や Actionsの方の問題なのかな、と思っていたりします。

## Expected behavior / 期待される挙動
bundleボタンが表示され、ライブラリ展開前と展開後のコードが切り替わるようになるという挙動が想定される挙動です。

他の人のページのソースコードを見てみると、展開前と展開後のどちらかのhighlightタグにはdisplay noneがついていて、CopyとBundleのボタンのタグが埋め込まれている。
![image](https://github.com/online-judge-tools/verification-helper/assets/33309829/72cf52e1-bce7-4e6a-89af-df24ac0c67c6)

## Actual behavior / 実際の挙動
bundleボタンが表示されず、ライブラリ展開前と展開後のコードが2つ縦に並ぶという挙動になっています。

[実際のドキュメントページ](https://nafmo.dev/library/example.test.cpp)

また、highlightタグにはdisplay noneのstyleはついておらず、ボタンのタグも埋め込まれていないようです。
![image](https://github.com/online-judge-tools/verification-helper/assets/33309829/7f6147d3-7f68-46b8-8dcf-47b569c6806f)

## Other notes / その他
別の新規リポジトリでも同じことが起こりました。僕の環境だけ発生するものであれば申し訳ないのですが、確認していただけると幸いです。

よろしくお願いいたします。

**Comment by kzrnm** [comment]
@Nafmo2 https 環境(例: https://nafmo.dev/library/example.test.cpp) から http の http://nafmo.dev/library/assets/js/copy-button.js を読み込もうとして読み込めてないのが原因のようです。

ただ、このリポジトリは現在メンテナンスされてない状況ですので、修正は見込めないかと思います。

このリポジトリをもとにした私のライブラリで良ければきちんと動作するかと思います。

https://competitive-verifier.github.io/competitive-verifier/installer.ja.html

## fork しての動作確認

**出力されるページ**
https://competitive-verifier.github.io/zzz_Nafmo2_library/

**適用した際の差分**
https://github.com/competitive-verifier/zzz_Nafmo2_library/compare/83b683043f61e2d7c7d26cd97726a3e3bd5c5995...main

**Comment by Nafmo2** [comment]
@kzrnm ご指摘ありがとうございます。自分のページのソースを呼んだ際に、たしかにhttpから読んでいるのを確認できました。

ただ、インストールマニュアルにある一例の[beetさん](https://beet-aizu.github.io/library/)のページはhttps環境であり、かつ https://beet-aizu.github.io/library/assets/js/copy-button.js を読み込むような設定になっております。

そのため、なんらかの方法でhttpsも読める...とは思っているのですが、どこが違うのかわかっていないと言う感じですね。  
ひとまず原因の特定とForkしての動作確認までありがとうございました。助かりました。

**Comment by Nafmo2** [comment]
# 原因
jekyllの仕様により発生する問題であった。[jekyllのリポジトリのIssue](https://github.com/jekyll/jekyll/issues/5590)にある解決策により解決することができた。そのため本件をCloseとします。

# 解決策
`.verify-helper/docs/_config.yml` に以下を追記する。

`url: "https://nafmo.dev"`

参考：https://github.com/Nafmo2/library/commit/974a4a87b99ce0ea5072efa360860557bfabb03b

※リポジトリ名などは含まないように注意
