### ISSUE TITLE
Failled to resolve dependency to the Python standard libraries

### ISSUE THREAD

**Issue by edomonndo** [online-judge-tools/verification-helper#414]
## Summary / 概要

If user’s py files include the link to standard libraries, the check mark icon is not applied in the doc file.

## Steps to reproduce / 再現方法

1. Make a Python file with imports (e.g. ` import typing `)
2. Make appropriate test files
3. Run `oj-verify`

environments:

-   version: v5.6.0

## Expected behavior / 期待される挙動

The links to standard libraries are ignored when making doc files. 

## Actual behavior / 実際の挙動

The links are not resolved and the the library page does not show `verified with`. 

## Other notes / その他

Please let me know if this issues could be resolved by config file or any other setting.

-   Will you try to create a pull request?
    -   yes / no

**Comment by koba-e964** [comment]
The following simple patch should resolve this issue. (PR: https://github.com/online-judge-tools/verification-helper/pull/415)
```diff
diff --git a/onlinejudge_verify/languages/python.py b/onlinejudge_verify/languages/python.py
index d31d2f5..cd3c1a2 100644
--- a/onlinejudge_verify/languages/python.py
+++ b/onlinejudge_verify/languages/python.py
@@ -57,7 +57,7 @@ def _python_list_depending_files(path: pathlib.Path, basedir: pathlib.Path) -> L
     )
     try:
         executor = concurrent.futures.ThreadPoolExecutor()
-        future = executor.submit(importlab.graph.ImportGraph.create, env, [str(path)])
+        future = executor.submit(importlab.graph.ImportGraph.create, env, [str(path)], trim=True)
         if platform.uname().system == 'Windows':
             timeout = 5.0  # 1.0 sec causes timeout on CI using Windows
         else:
```
