### ISSUE TITLE
Use a template engine to generate documents

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/verification-helper#46]
現状は `docs.py` の中で手動で HTML を錬成していますが、template engine を利用すると楽になります。現状すでに動いているので置き換えてもすぐにはうれしさはないですが、一度やってしまえば開発速度は上がって長期的に楽になるはずです。

Python だと Jinja2 というのがおすすめです (最もよく使われているものなので)。
また、 Jekyll が Ruby 製の Liquid という template engine を使っていてこれと併せて 2 種類の異なる template engine が併存するのはなんとなく嫌な感じがしますが、これは仕方ないので無視するしかないと考えています。

**Comment by tsutaj** [comment]
情報ありがとうございます！！チェックします

**Comment by kmyk** [comment]
これ終わってる
