### ISSUE TITLE
verification using AtCoder and/or Codeforces

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/verification-helper#74]
自動で提出して AC したか自動で確認すればよいので、可能です。

わりと簡単に実装できますが、完全自動化すると AtCoder への負荷でおこられます。
たぶん「ローカルからしか使えない」「1ファイルずつ手動で `oj-verify submit hoge.test.cpp` を実行しないとだめ」「ところどころ sleep を挟む」ぐらいに制限をかければぎりぎり許されるはず。便利にするとおこられだし不便にするとつらいので難しいが、AtCoder の問題を verify に使いたさはあるのでやってみてもよいかも？

**Comment by kmyk** [comment]
テストファイルは 300 個とか越えるので手動提出は現実的でない。自動提出も BAN される。無理です

**Comment by kmyk** [comment]
Many online judges don't distribute their test cases.
It's possible to submit directly (like vjudge), but **there is the problem about scalability**.

---

The number of test files becomes too large. For example, @beet-aizu's [library](https://beet-aizu.github.io/library/) has about 300 test files now (i.e., without support for AtCoder nor Codeforces). It will easily reach 1000 files when AtCoder and Codeforces are supported.

There are some possible methods. Some methods including steps using hands (e.g. submitting via web browsers and reporting the results by hands) are apparently impossible. For automatically submitting, possibilities are following:

1. Submitting from users' local environments
1. Submitting from GitHub Action
1. Using some proxy servers like vjudge

But using any method, automatically submitting has same difficulties:

1. Politeness: We'll be banned if making too many submissions. The online judges like Codeforces don't welcome to such automatically submitting. (vjudge is just tolerated because users request submissions by hands and make only few submissions.)
1. Speed: Adding waits makes verification too slow. If adding waits 1 minute per 1 file for politeness, it takes 10 minutes for 10 files and 5 hours for 300 files. The token of GitHub Actions becomes unstable in 20 minutes (#51), and entirely expires in 1 hour.
1. Cost: The cost about implementation and maintaining. It's possible but very troublesome to implement features to logging in, submitting, and getting results for many online judges. Using vjudge as a proxy (suggested by https://codeforces.com/profile/Devil) may be a good idea to decrease costs.

It one takes care about (1.) Politeness, then we cannot ignore the (2.) Speed. And using any method, the (3.) Cost to implement is relatively large for the benefits.
If someone sends a nice implementation, of course I'll merge it.

**Comment by kmyk** [comment]
要望としてはあるので reopen しておく (解決はしなさそうだけど)

**Comment by kjnh10** [comment]
AtCoderで一部の問題はテストケースが公開されていますが
それらに対してだけでもoj download --systemを動くようにすることはできませんか？

問題のURLとテストケースのURLが機械的には判定出来なそう雰囲気なので、
テストとして使いたい人が辞書にその都度登録していくような運用ならできるのかなという気がします。

**Comment by kmyk** [comment]
@kjnh10 

> AtCoderで一部の問題はテストケースが公開されていますが
それらに対してだけでもoj download --systemを動くようにすることはできませんか？

はい、@kjnh10 さんの言うようにすればできます。
実際に類似のことをある程度の部分までしている例はあります: https://greasyfork.org/ja/scripts/371832-atcoder-testcase-extension (GitHub: https://github.com/tatsumack/atcoder-testcase-extension)

しかし、しんどいので私は実装もメンテもあまりしたくないです。(ユーザからは望まれてるので、よく書けたプルリクが来てしまった場合はマージせざるをえないみたいなところはありますが……)
これは以下のふたつの課題のためです:

1. Dropbox の操作が難しい
    - Dropbox は scraping を歓迎していません。サイトが AtCoder などと違って複雑かつ頻繁に変更が入るので、scraping は開発もメンテもしんどいはずです。ちなみにユーザにとっては楽です
    - API の利用は推奨されていますが、開発者にとってもユーザにとってもしんどいです。開発者側は OAuth 用のサーバを立てて維持管理をする必要がありますし、ユーザ側は Dropbox のアカウントを作って認証その他をする必要があります (たぶん)
    - 参考: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/download-file-using-python-API-frpm-another-user/td-p/191824
2. AtCoder はテストケースのダウンロードの自動化を歓迎していない
   - 「望まれているのは分かるけど、機械的にダウンロードできるようにしちゃうと他のオンラインジャッジに問題を丸パクリされるのでつらい」みたいな話があります。実装前に chokudai さんに話を通す必要があります

**Comment by kmyk** [comment]
AtCoder TestCase Extension を読むとそんなに闇っぽくないし、もしかすると scraping いけるのかも？

**Comment by kjnh10** [comment]
回答ありがとうございます。
1については少し調べてみてますが出来たとしても（私の技量だと）面倒そうな感じはします。
1がクリアできても２がクリアされないことにはという感じですし。

別の方法としてローカルのテストフォルダはユーザーが自前で用意して下記のような記法を許すようにするのはどうでしょうか？
#define PROBLEM "../../local_cases/abc165_e"

第三者がライブラリを眺めた時に本当にその問題でverifyされてるかが怪しくなるのが少し嫌かなという気はしますが。

ちなみにそこまで強い要望ではないです。aoj, yosupo judge, yukicoderで基本的には十分という気
もしていますので。ただやはりAtCoderの問題も扱えると上記のコンテストから探す手間が省けるのでありがたいという気はします。

**Comment by kmyk** [comment]
テストケースを自前で用意できるようにする方向をやるべきでない理由は特にないですが、やってもあまりうれしさがないと考えています。次のふたつが根拠です。

- テストケースを自分で書くのはしんどい。ランダムケースだけだとたいてい弱いし、丁寧なケースを作り込むのは難しい
  - そういう作業を自分でやるのならいっそ Library Checker に投稿した方がよい
- 現状でも http://judge.u-aizu.ac.jp/onlinejudge/description.jsp?id=ITP1_1_A を指定して `hoge.test.cpp` の中でランダムケースを生成することでだいたい同じことができ、こちらの方が圧倒的に楽

**Comment by kjnh10** [comment]
自前で用意する、の表現が良くなかったです。副次的なメリットとしてそれもあるんですが、基本的にはAtCoderのテストケースをDropboxから手でダウンロードしてきてレポジトリ内に置く使い方を想定していました。

**Comment by kmyk** [comment]
理解しました。そうするとテストケースを書かなくてよくて多少は楽そうですが、すでに指摘してくれているように CI 上でのテストができないのがつらそうです。

**Comment by kjnh10** [comment]
レポジトリ内にテストケースをおいておいたらCI上でも動く（ように実装できる）と思っていたのですが、そうでもないのですかね？

**Comment by kmyk** [comment]
「レポジトリ内にテストケースをおいておいたらCI上でも動く」は正しいです。
しかし「AtCoderのテストケースをDropboxから手でダウンロードしてきてレポジトリ内に置く」をやると著作権的な問題が発生します。無断での再配布はまずいので、これも chokudai さんに許可を取る必要があります。

**Comment by kmyk** [comment]
https://github.com/online-judge-tools/api-client/issues/60

**Comment by qryxip** [comment]
> 2. 素朴な実装しかされてなさそう
>     - AtCoder のテストケースの Dropbox は人間の手によって暖かみのある管理をされているので、それなりに汚ないです (例: [takoha-cpp/WrongAnswer が苦しんでいる様子](https://github.com/takoha-cpp/WrongAnswer#dropbox%E4%B8%8A%E5%85%AC%E9%96%8B%E3%83%87%E3%83%BC%E3%82%BF%E3%81%AE%E5%95%8F%E9%A1%8C))。そのあたりの対策がなくてまだ枯れてなさそうに見えます

コンテスト名の対応:

https://github.com/qryxip/snowchains/blob/b3f916e1999063d774c312e1fb1af975912e4078/snowchains_core/resources/dropbox-path-prefixes.json

外部コンテストがあるたびに更新していくしかなさそう。

ゴミファイルについてはまだ調べてませんがwaの該当部分を見るに人の暖かみは数パターンしかないようなのでこれでなんとかなる?

https://github.com/takoha-cpp/WrongAnswer/blob/5ad8434af14163da3f60e391d7f83c50fd3b7a90/wrong_answer/main.py#L276-L284

**Comment by kmyk** [comment]
AtCoder is now supported. Codeforces is impossible.
